services:
  # Our Rust backend service
  backend:
    build:
      context: .
      dockerfile: ephemeral_backend/Dockerfile
    image: ephemeral-backend
    restart: unless-stopped
    network_mode: "host" 
    environment:
      - RUST_LOG=info
      - REDIS_URL=${REDIS_URL}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    depends_on:
      - redis
      - minio

  # The Redis database service (for local dev, not used in prod)
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    expose:
      - "6379"

  # The MinIO storage service (for local dev, not used in prod)
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

