# ephemeral/netlify.toml

[build]
# This is the command Netlify will run from the root of your repository.
# It installs the CLI and then builds the `ephemeral_web` package.
command = "cargo install dioxus-cli --force && dx build --release --platform web --package ephemeral_web"

# as determined by the Dioxus CLI's default behavior.
publish = "target/dx/ephemeral_web/release/web/public"

# Single-Page Application (SPA) routing.
# It tells Netlify how to handle deep links and page reloads.
[[redirects]]
# For any path that is requested...
from = "/*"
# ...serve the main index.html file instead.
to = "/index.html"
# Respond with a 200 OK status to keep the original URL in the browser's address bar.
status = 200
