# ephemeral/netlify.toml

[build]
# This is the command Netlify will run from the root of your repository.
# It specifically builds the `ephemeral_web` package.
command = "dx build --release --package ephemeral_web"

# FIX: This is the correct path to the build output for a workspace project.
# It points directly to the final, public-ready files.
publish = "target/dx/ephemeral_web/release/web/public"
