# ephemeral/netlify.toml

[build]
# This is the command Netlify will run from the root of your repository.
# It installs the CLI and then builds the `ephemeral_web` package.
# The `--out dist` flag explicitly tells Dioxus to put the final website in a folder named "dist".
command = "cargo install dioxus-cli && dx build --release --package ephemeral_web --out dist"

# This is the directory that Netlify will deploy.
publish = "dist"
