name: Build & Deploy frontend to Netlify

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (stable) and add wasm target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Deploy to Netlify (via npx)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          # Deploy the compiled Dioxus web build to Netlify using npx to avoid
          # global npm installs on the runner.
          # dx outputs to: ephemeral_web/target/dx/ephemeral_web/release/web/public
          BUILD_DIR=ephemeral_web/target/dx/ephemeral_web/release/web/public

          if [ -z "$NETLIFY_AUTH_TOKEN" ]; then
            echo "NETLIFY_AUTH_TOKEN is not set. Add it to repository secrets as NETLIFY_AUTH_TOKEN." >&2
            exit 1
          fi
          if [ -z "$NETLIFY_SITE_ID" ]; then
            echo "NETLIFY_SITE_ID is not set. Add it to repository secrets as NETLIFY_SITE_ID." >&2
            exit 1
          fi
          if [ ! -d "$BUILD_DIR" ]; then
            echo "Build directory not found: $BUILD_DIR" >&2
            ls -la ephemeral_web/target/dx || true
            exit 1
          fi

          # Show netlify-cli version (installed via npx) for debugging.
          npx --yes netlify-cli@latest --version || true

          # Quick check: ensure the token can see the site (helpful diagnostic).
          npx --yes netlify-cli@latest sites:get --site "$NETLIFY_SITE_ID" --auth "$NETLIFY_AUTH_TOKEN" || true

          # Deploy to production
          npx --yes netlify-cli@latest deploy --dir="$BUILD_DIR" --auth "$NETLIFY_AUTH_TOKEN" --site "$NETLIFY_SITE_ID" --prod

      - name: Build Dioxus web (release)
        run: |
          cd ephemeral_web
          dx build --release --platform web

      - name: Setup Node (for netlify-cli)
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install netlify-cli
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          # Deploy the compiled static site to Netlify
          netlify deploy --dir=ephemeral_web/dist --auth "$NETLIFY_AUTH_TOKEN" --site "$NETLIFY_SITE_ID" --prod
