name: Build & Deploy frontend to Netlify

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install netlify-cli
        run: npm install -g netlify-cli

      - name: Install Rust stable and wasm target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build WASM package
        run: |
          cd ephemeral_web
          echo "Building WASM package with wasm-pack..."
          wasm-pack build --target web --release
          echo "WASM build completed."

      - name: Prepare deployment files
        run: |
          cd ephemeral_web
          mkdir -p dist/pkg

          # Copy the built files
          cp pkg/* dist/pkg/
          cp index.html dist/

          # Add redirects for SPA routing
          echo "/*    /index.html   200" > dist/_redirects

          echo "Final dist contents:"
          ls -la dist/

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          cd ephemeral_web
          echo "Deploying these files to Netlify:"
          ls -la dist/

          netlify deploy --dir=dist --auth "$NETLIFY_AUTH_TOKEN" --site "$NETLIFY_SITE_ID" --prod
