name: Build & Deploy frontend to Netlify

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install netlify-cli
        run: npm install -g netlify-cli

      - name: Install Rust (stable) and add wasm target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install Dioxus CLI
        run: cargo install dioxus-cli

      - name: Build Dioxus web (release)
        run: |
          cd ephemeral_web
          dx build --release --platform web

      - name: Prepare dist directory
        run: |
          cd ephemeral_web
          # Create redirects file for SPA routing
          mkdir -p dist
          echo "/*    /index.html   200" > dist/_redirects
          echo "Dist directory prepared with redirects"

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          cd ephemeral_web
          echo "Deploying from dist directory:"
          ls -la dist
          netlify deploy --dir=dist --auth "$NETLIFY_AUTH_TOKEN" --site "$NETLIFY_SITE_ID" --prod
