permissions:
  contents: write

name: Build & Deploy frontend to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (stable) and add wasm target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install dioxus-cli
        run: cargo install --locked dioxus-cli

      - name: Add cargo bin to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Cache cargo registry and git
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo target
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-

      - name: Build Dioxus web (release)
        run: |
          cd ephemeral_web
          dx build --release --platform web

          # Create 404.html for SPA routing on GitHub Pages
          BUILD_DIR="target/dx/ephemeral_web/release/web/public"
          if [ -f "$BUILD_DIR/index.html" ]; then
            cp "$BUILD_DIR/index.html" "$BUILD_DIR/404.html"
            echo "Created 404.html for SPA routing"
          fi

          # Verify build directory exists and has content
          echo "Build directory contents:"
          if [ -d "$BUILD_DIR" ]; then
            ls -la "$BUILD_DIR/"
          else
            echo "Build directory not found at $BUILD_DIR"
            find . -type d -name "public" | head -5
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ephemeral_web/target/dx/ephemeral_web/release/web/public
          enable_jekyll: false
