name: Build & Deploy frontend to Netlify

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable and wasm target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install Dioxus CLI
        run: cargo install dioxus-cli --version 0.5.1

      - name: Build Dioxus web app
        run: |
          cd ephemeral_web
          echo "Building Dioxus app with dx command..."
          dx build --release --platform web
          echo "Dioxus build completed."

      - name: Verify build output exists
        run: |
          cd ephemeral_web
          BUILD_DIR="target/dx/ephemeral_web/release/web/public"
          if [ -d "$BUILD_DIR" ]; then
            echo "Build directory found. Contents:"
            ls -la "$BUILD_DIR"
          else
            echo "Build directory not found. Looking for it..."
            find . -type d -name "public" | head -10
            echo "Target directory contents:"
            find target -type f | head -20
          fi

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          cd ephemeral_web/target/dx/ephemeral_web/release/web/public
          echo "Deploying from directory: $(pwd)"
          echo "Contents to deploy:"
          ls -la

          # Add redirects file for SPA routing if it doesn't exist
          if [ ! -f "_redirects" ]; then
            echo "/*    /index.html   200" > _redirects
            echo "Created _redirects file"
          fi

          npx netlify-cli deploy --auth "$NETLIFY_AUTH_TOKEN" --site "$NETLIFY_SITE_ID" --prod
