name: Build & Deploy frontend to Netlify

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install netlify-cli
        run: npm install -g netlify-cli

      - name: Install Rust stable and wasm target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install latest Dioxus CLI from main branch
        run: |
          # Install the latest Dioxus CLI that supports Cargo.lock v4
          cargo install dioxus-cli --git https://github.com/DioxusLabs/dioxus --branch main

      - name: Build Dioxus web app
        run: |
          cd ephemeral_web
          echo "Building Dioxus app with dx command..."
          dx build --release --platform web
          echo "Dioxus build completed."

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          # Navigate to the correct build output directory (from workspace root)
          cd target/dx/ephemeral_web/release/web/public
          echo "Deploying from directory: $(pwd)"
          echo "Contents to deploy:"
          ls -la

          # Add redirects file for SPA routing if it doesn't exist
          if [ ! -f "_redirects" ]; then
            echo "/*    /index.html   200" > _redirects
            echo "Created _redirects file"
          fi

          npx netlify-cli deploy --auth "$NETLIFY_AUTH_TOKEN" --site "$NETLIFY_SITE_ID" --prod
